<?php

namespace Database\Seeders;

use App\Models\Archer;
use App\Models\Club;
use App\Models\Coach;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DummyDataSeeder extends Seeder
{
    public function run(): void
    {
        // ─── 5 Clubs ─────────────────────────────────────────────────────────
        $clubsData = [
            [
                'name'                => 'Selangor Archery Club',
                'description'         => 'Premier archery club serving Selangor and Klang Valley archers since 1985.',
                'location'            => 'Shah Alam, Selangor',
                'contact_email'       => 'info@selangorarchery.my',
                'contact_phone'       => '03-55101234',
                'website'             => 'https://selangorarchery.my',
                'address'             => 'Kompleks Sukan Shah Alam, Persiaran Majlis 40150 Shah Alam',
                'state'               => 'Selangor',
                'founded_year'        => 1985,
                'registration_number' => 'PPM-009-14-15052001',
                'active'              => true,
            ],
            [
                'name'                => 'Kelab Memanah Kuala Lumpur',
                'description'         => 'City-based club for recurve and compound archers in the capital.',
                'location'            => 'Cheras, Kuala Lumpur',
                'contact_email'       => 'admin@kmkl.my',
                'contact_phone'       => '03-91023456',
                'website'             => null,
                'address'             => 'Pusat Sukan Cheras, Jalan Cochrane 55100 Kuala Lumpur',
                'state'               => 'Kuala Lumpur',
                'founded_year'        => 1998,
                'registration_number' => 'PPM-014-11-22112003',
                'active'              => true,
            ],
            [
                'name'                => 'Persatuan Memanah Johor',
                'description'         => 'Official archery association for Johor state team development.',
                'location'            => 'Johor Bahru, Johor',
                'contact_email'       => 'pmjohor@gmail.com',
                'contact_phone'       => '07-2234567',
                'website'             => null,
                'address'             => 'Stadium Larkin, Jalan Garuda 80350 Johor Bahru',
                'state'               => 'Johor',
                'founded_year'        => 2002,
                'registration_number' => 'PPM-001-07-03062005',
                'active'              => true,
            ],
            [
                'name'                => 'Penang Archers Society',
                'description'         => 'Penang\'s most active archery club, hosting regular club leagues.',
                'location'            => 'Georgetown, Pulau Pinang',
                'contact_email'       => 'info@penangarchers.my',
                'contact_phone'       => '04-2615678',
                'website'             => 'https://penangarchers.my',
                'address'             => 'Padang Polo, Jalan Air Itam 10050 Georgetown',
                'state'               => 'Pulau Pinang',
                'founded_year'        => 1991,
                'registration_number' => 'PPM-007-04-14091992',
                'active'              => true,
            ],
            [
                'name'                => 'Kelab Memanah Perak',
                'description'         => 'Training hub for recurve, compound and barebow archers in Perak.',
                'location'            => 'Ipoh, Perak',
                'contact_email'       => 'kmperak@outlook.com',
                'contact_phone'       => '05-5457890',
                'website'             => null,
                'address'             => 'Stadium Indera Mulia, Jalan Stadium 30300 Ipoh',
                'state'               => 'Perak',
                'founded_year'        => 1994,
                'registration_number' => 'PPM-004-05-08031995',
                'active'              => true,
            ],
        ];

        $clubs = [];
        foreach ($clubsData as $data) {
            $clubs[] = Club::firstOrCreate(['name' => $data['name']], $data);
        }

        // ─── 5 Coaches (1 per club) ───────────────────────────────────────────
        $coachesData = [
            [
                'club'           => 'Selangor Archery Club',
                'name'           => 'Ahmad Fadzli bin Mohd Noor',
                'email'          => 'fadzli.coach@example.my',
                'dob'            => '1975-06-14',
                'gender'         => 'male',
                'phone'          => '012-3112233',
                'team'           => 'Selangor State Team',
                'state'          => 'Selangor',
                'postcode'       => '40150',
                'address_line'   => 'No. 7, Jalan Damai 2, Taman Damai',
                'coaching_level' => 'Level 3',
                'national_team'  => true,
                'notes'          => 'Former national team archer, 3x SEA Games participant. Specialises in recurve technique.',
            ],
            [
                'club'           => 'Kelab Memanah Kuala Lumpur',
                'name'           => 'Nurul Huda binti Ismail',
                'email'          => 'nurul.huda.coach@example.my',
                'dob'            => '1982-03-28',
                'gender'         => 'female',
                'phone'          => '013-4445566',
                'team'           => 'KL State Team',
                'state'          => 'Kuala Lumpur',
                'postcode'       => '55100',
                'address_line'   => 'Unit 12-4, Residensi Prima, Jalan Imbi',
                'coaching_level' => 'Level 2',
                'national_team'  => false,
                'notes'          => 'Focuses on youth development and mental performance coaching.',
            ],
            [
                'club'           => 'Persatuan Memanah Johor',
                'name'           => 'Mohd Rashdan bin Osman',
                'email'          => 'rashdan.coach@example.my',
                'dob'            => '1978-11-05',
                'gender'         => 'male',
                'phone'          => '017-7889900',
                'team'           => 'Johor State Team',
                'state'          => 'Johor',
                'postcode'       => '80350',
                'address_line'   => 'No. 32, Jalan Seroja, Taman Pelangi',
                'coaching_level' => 'Level 2',
                'national_team'  => false,
                'notes'          => 'Compound specialist with 12 years coaching experience.',
            ],
            [
                'club'           => 'Penang Archers Society',
                'name'           => 'Lim Beng Huat',
                'email'          => 'lim.bh.coach@example.my',
                'dob'            => '1968-07-19',
                'gender'         => 'male',
                'phone'          => '016-4321099',
                'team'           => 'Penang State Team',
                'state'          => 'Pulau Pinang',
                'postcode'       => '10050',
                'address_line'   => '22, Jalan Burmah, Georgetown',
                'coaching_level' => 'Level 1',
                'national_team'  => false,
                'notes'          => 'Senior coach and club founder. Barebow and traditional archery specialist.',
            ],
            [
                'club'           => 'Kelab Memanah Perak',
                'name'           => 'Kamaliah binti Zulkifli',
                'email'          => 'kamaliah.coach@example.my',
                'dob'            => '1985-09-30',
                'gender'         => 'female',
                'phone'          => '019-6677889',
                'team'           => 'Perak State Team',
                'state'          => 'Perak',
                'postcode'       => '30300',
                'address_line'   => 'No. 5, Lorong Cempaka 3, Taman Cempaka',
                'coaching_level' => 'Kursus Asas Kejurulatihan',
                'national_team'  => false,
                'notes'          => 'Junior development coach with background in sports science.',
            ],
        ];

        foreach ($coachesData as $data) {
            if (User::where('email', $data['email'])->exists()) {
                continue;
            }
            $club = collect($clubs)->firstWhere('name', $data['club']);
            $user = User::create([
                'name'     => $data['name'],
                'email'    => $data['email'],
                'password' => Hash::make('password'),
                'role'     => 'coach',
                'club_id'  => $club->id,
            ]);
            Coach::create([
                'user_id'        => $user->id,
                'club_id'        => $club->id,
                'date_of_birth'  => $data['dob'],
                'gender'         => $data['gender'],
                'phone'          => $data['phone'],
                'team'           => $data['team'],
                'state'          => $data['state'],
                'country'        => 'Malaysia',
                'address_line'   => $data['address_line'],
                'postcode'       => $data['postcode'],
                'coaching_level' => $data['coaching_level'],
                'national_team'  => $data['national_team'],
                'notes'          => $data['notes'],
                'active'         => true,
            ]);
        }

        // ─── 15 Archers (3 per club) ─────────────────────────────────────────
        $archersData = [
            // Selangor Archery Club
            [
                'club'           => 'Selangor Archery Club',
                'name'           => 'Muhammad Haziq bin Zainudin',
                'email'          => 'haziq.archer@example.my',
                'dob'            => '1998-03-15',
                'gender'         => 'male',
                'phone'          => '012-3456789',
                'hand'           => 'right',
                'team'           => 'Selangor State Team',
                'state'          => 'Selangor',
                'postcode'       => '40150',
                'address_line'   => 'No. 12, Jalan Bahagia 3, Taman Bahagia',
                'divisions'      => ['Recurve'],
                'classification' => '1st Class',
                'national_team'  => 'Podium',
                'bow_style'      => 'Recurve',
                'limb_poundage'  => 38,
                'actual_poundage'=> 36,
                'arrow_type'     => 'Carbon',
                'arrow_size'     => '1816',
                'pb_unofficial_72_score' => 642,
                'pb_unofficial_72_date'  => '2024-08-10',
                'pb_official_72_score'   => 628,
                'pb_official_72_date'    => '2024-06-15',
                'pb_official_72_tournament' => 'Kejohanan Memanah Terbuka Selangor 2024',
                'notes'          => 'National squad member. Strong anchor, needs work on release timing.',
            ],
            [
                'club'           => 'Selangor Archery Club',
                'name'           => 'Siti Nurashikin binti Wahab',
                'email'          => 'ashikin.archer@example.my',
                'dob'            => '2003-11-22',
                'gender'         => 'female',
                'phone'          => '013-8887766',
                'hand'           => 'right',
                'team'           => 'Selangor State Team',
                'state'          => 'Selangor',
                'postcode'       => '41000',
                'address_line'   => 'No. 3, Jalan Kenanga 7, Taman Kenanga',
                'divisions'      => ['Recurve', 'Barebow'],
                'classification' => 'Bowman',
                'national_team'  => 'No',
                'bow_style'      => 'Recurve',
                'limb_poundage'  => 26,
                'actual_poundage'=> 24,
                'arrow_type'     => 'Aluminium',
                'arrow_size'     => '1516',
                'pb_unofficial_36_score' => 298,
                'pb_unofficial_36_date'  => '2025-01-20',
                'notes'          => 'U21 category. Consistent grouping, working on mental game.',
            ],
            [
                'club'           => 'Selangor Archery Club',
                'name'           => 'Tengku Arif Shah bin Tengku Azman',
                'email'          => 'arif.archer@example.my',
                'dob'            => '1985-07-04',
                'gender'         => 'male',
                'phone'          => '019-1234567',
                'hand'           => 'right',
                'team'           => 'Selangor State Team',
                'state'          => 'Selangor',
                'postcode'       => '40450',
                'address_line'   => 'No. 88, Jalan Sultan, Shah Alam',
                'divisions'      => ['Compound'],
                'classification' => 'Grand Bowman',
                'national_team'  => 'Pelapis Kebangsaan',
                'bow_style'      => 'Compound',
                'limb_poundage'  => 60,
                'actual_poundage'=> 58,
                'arrow_type'     => 'Carbon',
                'arrow_size'     => '400',
                'pb_unofficial_72_score' => 690,
                'pb_unofficial_72_date'  => '2024-11-03',
                'pb_official_72_score'   => 683,
                'pb_official_72_date'    => '2024-09-22',
                'pb_official_72_tournament' => 'Sukma 2024 Johor',
                'notes'          => 'Compound veteran, excellent at pressure shooting.',
            ],
            // Kelab Memanah Kuala Lumpur
            [
                'club'           => 'Kelab Memanah Kuala Lumpur',
                'name'           => 'Nurul Ain binti Razali',
                'email'          => 'nurain.archer@example.my',
                'dob'            => '2001-07-22',
                'gender'         => 'female',
                'phone'          => '013-4567890',
                'hand'           => 'right',
                'team'           => 'KL State Team',
                'state'          => 'Kuala Lumpur',
                'postcode'       => '55100',
                'address_line'   => 'Unit 5-3, Residensi Maju, Jalan Bukit Bintang',
                'divisions'      => ['Recurve'],
                'classification' => 'Bowman',
                'national_team'  => 'No',
                'bow_style'      => 'Recurve',
                'limb_poundage'  => 30,
                'actual_poundage'=> 28,
                'arrow_type'     => 'Carbon',
                'arrow_size'     => '1716',
                'pb_unofficial_36_score' => 312,
                'pb_unofficial_36_date'  => '2025-02-08',
                'notes'          => 'U23 rising talent. Consistent form in indoor rounds.',
            ],
            [
                'club'           => 'Kelab Memanah Kuala Lumpur',
                'name'           => 'Daniel Chong Wei Liang',
                'email'          => 'daniel.archer@example.my',
                'dob'            => '1993-04-17',
                'gender'         => 'male',
                'phone'          => '012-7654321',
                'hand'           => 'left',
                'team'           => 'KL State Team',
                'state'          => 'Kuala Lumpur',
                'postcode'       => '50350',
                'address_line'   => '14A, Jalan Duta, Bukit Damansara',
                'divisions'      => ['Recurve', 'Compound'],
                'classification' => '2nd Class',
                'national_team'  => 'No',
                'bow_style'      => 'Recurve',
                'limb_poundage'  => 42,
                'actual_poundage'=> 40,
                'arrow_type'     => 'Carbon',
                'arrow_size'     => '2013',
                'pb_unofficial_72_score' => 598,
                'pb_unofficial_72_date'  => '2024-10-15',
                'notes'          => 'Left-handed archer. Competes in both recurve and compound categories.',
            ],
            [
                'club'           => 'Kelab Memanah Kuala Lumpur',
                'name'           => 'Priya a/p Selvakumar',
                'email'          => 'priya.archer@example.my',
                'dob'            => '2007-08-11',
                'gender'         => 'female',
                'phone'          => '011-5566778',
                'hand'           => 'right',
                'team'           => 'KL State Team',
                'state'          => 'Kuala Lumpur',
                'postcode'       => '56000',
                'address_line'   => 'No. 22, Jalan Ampang Hilir, Ampang',
                'divisions'      => ['Recurve'],
                'classification' => null,
                'national_team'  => 'No',
                'bow_style'      => 'Recurve',
                'limb_poundage'  => 20,
                'actual_poundage'=> 18,
                'arrow_type'     => 'Aluminium',
                'arrow_size'     => '1514',
                'notes'          => 'U18 junior. Recently started club training, shows good potential.',
            ],
            // Persatuan Memanah Johor
            [
                'club'           => 'Persatuan Memanah Johor',
                'name'           => 'Mohd Faris bin Ramli',
                'email'          => 'faris.archer@example.my',
                'dob'            => '1996-12-30',
                'gender'         => 'male',
                'phone'          => '017-3344556',
                'hand'           => 'right',
                'team'           => 'Johor State Team',
                'state'          => 'Johor',
                'postcode'       => '80350',
                'address_line'   => 'No. 15, Jalan Dato Sulaiman, Johor Bahru',
                'divisions'      => ['Compound'],
                'classification' => '1st Class',
                'national_team'  => 'Pelapis Kebangsaan',
                'bow_style'      => 'Compound',
                'limb_poundage'  => 60,
                'actual_poundage'=> 57,
                'arrow_type'     => 'Carbon',
                'arrow_size'     => '500',
                'pb_unofficial_72_score' => 672,
                'pb_unofficial_72_date'  => '2024-12-01',
                'pb_official_72_score'   => 658,
                'pb_official_72_date'    => '2024-07-08',
                'pb_official_72_tournament' => 'Kejohanan Terbuka Johor 2024',
                'notes'          => 'Top compound archer in Johor. Strong under pressure.',
            ],
            [
                'club'           => 'Persatuan Memanah Johor',
                'name'           => 'Nur Farahana binti Zulkifli',
                'email'          => 'farahana.archer@example.my',
                'dob'            => '1999-05-16',
                'gender'         => 'female',
                'phone'          => '013-6667788',
                'hand'           => 'right',
                'team'           => 'Johor State Team',
                'state'          => 'Johor',
                'postcode'       => '81300',
                'address_line'   => 'No. 7, Jalan Mawar, Taman Molek',
                'divisions'      => ['Recurve', 'Barebow'],
                'classification' => '2nd Class',
                'national_team'  => 'No',
                'bow_style'      => 'Recurve',
                'limb_poundage'  => 32,
                'actual_poundage'=> 30,
                'arrow_type'     => 'Carbon',
                'arrow_size'     => '1816',
                'pb_unofficial_36_score' => 320,
                'pb_unofficial_36_date'  => '2025-01-05',
                'notes'          => 'Versatile archer competing in recurve and barebow divisions.',
            ],
            [
                'club'           => 'Persatuan Memanah Johor',
                'name'           => 'Hafizuddin bin Md Zain',
                'email'          => 'hafiz.archer@example.my',
                'dob'            => '2004-02-14',
                'gender'         => 'male',
                'phone'          => '014-9988776',
                'hand'           => 'right',
                'team'           => 'Johor State Team',
                'state'          => 'Johor',
                'postcode'       => '81200',
                'address_line'   => 'No. 21, Jalan Skudai 3, Taman Skudai',
                'divisions'      => ['Recurve'],
                'classification' => null,
                'national_team'  => 'No',
                'bow_style'      => 'Recurve',
                'limb_poundage'  => 24,
                'actual_poundage'=> 22,
                'arrow_type'     => 'Aluminium',
                'arrow_size'     => '1616',
                'notes'          => 'Junior archer (U21). First year competing at state level.',
            ],
            // Penang Archers Society
            [
                'club'           => 'Penang Archers Society',
                'name'           => 'Lee Chun Kiat',
                'email'          => 'lee.ck.archer@example.my',
                'dob'            => '1988-09-12',
                'gender'         => 'male',
                'phone'          => '011-2345678',
                'hand'           => 'right',
                'team'           => 'Penang State Team',
                'state'          => 'Pulau Pinang',
                'postcode'       => '10000',
                'address_line'   => '88-A, Jalan Penang, Georgetown',
                'divisions'      => ['Recurve', 'Compound'],
                'classification' => 'Grand Bowman',
                'national_team'  => 'No',
                'bow_style'      => 'Recurve',
                'limb_poundage'  => 44,
                'actual_poundage'=> 42,
                'arrow_type'     => 'Carbon',
                'arrow_size'     => '2013',
                'pb_unofficial_72_score' => 620,
                'pb_unofficial_72_date'  => '2024-05-20',
                'pb_official_72_score'   => 605,
                'pb_official_72_date'    => '2023-09-10',
                'pb_official_72_tournament' => 'Penang International Archery Open 2023',
                'notes'          => 'Club captain. Active in both local and national competitions.',
            ],
            [
                'club'           => 'Penang Archers Society',
                'name'           => 'Sumathy a/p Krishnan',
                'email'          => 'sumathy.archer@example.my',
                'dob'            => '2000-01-25',
                'gender'         => 'female',
                'phone'          => '016-9988123',
                'hand'           => 'right',
                'team'           => 'Penang State Team',
                'state'          => 'Pulau Pinang',
                'postcode'       => '10050',
                'address_line'   => 'No. 5, Jalan Air Itam Lama, Georgetown',
                'divisions'      => ['Barebow'],
                'classification' => '2nd Class',
                'national_team'  => 'No',
                'bow_style'      => 'Barebow',
                'limb_poundage'  => 28,
                'actual_poundage'=> 26,
                'arrow_type'     => 'Carbon',
                'arrow_size'     => '1716',
                'pb_unofficial_36_score' => 255,
                'pb_unofficial_36_date'  => '2024-09-14',
                'notes'          => 'Barebow specialist. Participates in field archery competitions.',
            ],
            [
                'club'           => 'Penang Archers Society',
                'name'           => 'Ahmad Ridhwan bin Shamsul',
                'email'          => 'ridhwan.archer@example.my',
                'dob'            => '2006-06-08',
                'gender'         => 'male',
                'phone'          => '012-6677334',
                'hand'           => 'right',
                'team'           => 'Penang State Team',
                'state'          => 'Pulau Pinang',
                'postcode'       => '11700',
                'address_line'   => 'No. 14, Jalan Sungai Dua, Gelugor',
                'divisions'      => ['Recurve'],
                'classification' => null,
                'national_team'  => 'No',
                'bow_style'      => 'Recurve',
                'limb_poundage'  => 22,
                'actual_poundage'=> 20,
                'arrow_type'     => 'Aluminium',
                'arrow_size'     => '1514',
                'notes'          => 'U18 junior with excellent focus and natural form.',
            ],
            // Kelab Memanah Perak
            [
                'club'           => 'Kelab Memanah Perak',
                'name'           => 'Rajendran s/o Subramaniam',
                'email'          => 'raja.archer@example.my',
                'dob'            => '1982-11-08',
                'gender'         => 'male',
                'phone'          => '016-7891234',
                'hand'           => 'right',
                'team'           => 'Perak State Team',
                'state'          => 'Perak',
                'postcode'       => '30100',
                'address_line'   => 'No. 8, Lorong Damai, Taman Damai Jaya',
                'divisions'      => ['Compound', 'Traditional'],
                'classification' => 'Grand Bowman',
                'national_team'  => 'No',
                'bow_style'      => 'Compound',
                'limb_poundage'  => 58,
                'actual_poundage'=> 55,
                'arrow_type'     => 'Carbon',
                'arrow_size'     => '400',
                'pb_unofficial_72_score' => 665,
                'pb_unofficial_72_date'  => '2024-04-18',
                'pb_official_72_score'   => 651,
                'pb_official_72_date'    => '2024-02-25',
                'pb_official_72_tournament' => 'Kejohanan Terbuka Perak 2024',
                'notes'          => 'Masters category. Compound and traditional expert, mentors juniors.',
            ],
            [
                'club'           => 'Kelab Memanah Perak',
                'name'           => 'Norafizah binti Harun',
                'email'          => 'afizah.archer@example.my',
                'dob'            => '1994-08-19',
                'gender'         => 'female',
                'phone'          => '013-5544332',
                'hand'           => 'right',
                'team'           => 'Perak State Team',
                'state'          => 'Perak',
                'postcode'       => '31400',
                'address_line'   => 'No. 6, Jalan Bunga Tanjung, Taiping',
                'divisions'      => ['Recurve'],
                'classification' => '1st Class',
                'national_team'  => 'No',
                'bow_style'      => 'Recurve',
                'limb_poundage'  => 36,
                'actual_poundage'=> 34,
                'arrow_type'     => 'Carbon',
                'arrow_size'     => '1816',
                'pb_unofficial_72_score' => 590,
                'pb_unofficial_72_date'  => '2024-08-30',
                'pb_official_72_score'   => 574,
                'pb_official_72_date'    => '2024-07-12',
                'pb_official_72_tournament' => 'Kejohanan Memanah MSN Perak 2024',
                'notes'          => 'Consistent performer. Aiming for national squad selection.',
            ],
            [
                'club'           => 'Kelab Memanah Perak',
                'name'           => 'Izzat Hakim bin Azhari',
                'email'          => 'izzat.archer@example.my',
                'dob'            => '2005-04-03',
                'gender'         => 'male',
                'phone'          => '019-2233441',
                'hand'           => 'right',
                'team'           => 'Perak State Team',
                'state'          => 'Perak',
                'postcode'       => '30450',
                'address_line'   => 'No. 3, Jalan Cempaka, Meru',
                'divisions'      => ['Recurve', 'Barebow'],
                'classification' => null,
                'national_team'  => 'No',
                'bow_style'      => 'Recurve',
                'limb_poundage'  => 26,
                'actual_poundage'=> 24,
                'arrow_type'     => 'Aluminium',
                'arrow_size'     => '1616',
                'notes'          => 'U21 junior with strong training commitment.',
            ],
        ];

        foreach ($archersData as $data) {
            if (User::where('email', $data['email'])->exists()) {
                continue;
            }
            $club = collect($clubs)->firstWhere('name', $data['club']);
            $user = User::create([
                'name'     => $data['name'],
                'email'    => $data['email'],
                'password' => Hash::make('password'),
                'role'     => 'archer',
                'club_id'  => $club->id,
            ]);
            Archer::create([
                'user_id'                   => $user->id,
                'club_id'                   => $club->id,
                'date_of_birth'             => $data['dob'],
                'gender'                    => $data['gender'],
                'phone'                     => $data['phone'],
                'hand'                      => $data['hand'],
                'team'                      => $data['team'],
                'state'                     => $data['state'],
                'country'                   => 'Malaysia',
                'address_line'              => $data['address_line'],
                'postcode'                  => $data['postcode'],
                'address_state'             => $data['state'],
                'divisions'                 => $data['divisions'],
                'classification'            => $data['classification'] ?? null,
                'national_team'             => $data['national_team'],
                'bow_style'                 => $data['bow_style'] ?? null,
                'limb_poundage'             => $data['limb_poundage'] ?? null,
                'actual_poundage'           => $data['actual_poundage'] ?? null,
                'arrow_type'                => $data['arrow_type'] ?? null,
                'arrow_size'                => $data['arrow_size'] ?? null,
                'pb_unofficial_36_score'    => $data['pb_unofficial_36_score'] ?? null,
                'pb_unofficial_36_date'     => $data['pb_unofficial_36_date'] ?? null,
                'pb_unofficial_72_score'    => $data['pb_unofficial_72_score'] ?? null,
                'pb_unofficial_72_date'     => $data['pb_unofficial_72_date'] ?? null,
                'pb_official_72_score'      => $data['pb_official_72_score'] ?? null,
                'pb_official_72_date'       => $data['pb_official_72_date'] ?? null,
                'pb_official_72_tournament' => $data['pb_official_72_tournament'] ?? null,
                'notes'                     => $data['notes'] ?? null,
                'active'                    => true,
                'status'                    => 'active',
            ]);
        }
    }
}
